- name: install packages
  tags: packages
  apt:
    name: "{{ base_packages }}"
    install_recommends: false
    update_cache: true
    autoclean: true
    autoremove: true
    state: present

- name: install python packages
  apt:
    name:
      - "python3-pip"
      - "python3-dev"
      - "python3-setuptools"
      - "python-is-python3"
      - "virtualenv"
    install_recommends: false

- name: set sysctl entries
  tags: sysctl
  sysctl:
    name: "{{ sysctl.name }}"
    value: "{{ sysctl.value }}"
    state: present
    sysctl_set: true
  loop: "{{ base_sysctl }}"
  loop_control:
    loop_var: "sysctl"
    label: "{{ sysctl.name }}"
  when: base_sysctl is defined

- name: manage limits.conf
  tags: limits
  pam_limits:
  args: "{{ limit }}"
  loop: "{{ base_limits }}"
  loop_control:
    loop_var: "limit"
    label: "{{ limit.domain }} {{ limit.limit_item }}:{{ limit.limit_type }}"
  when: base_limits is defined

- name: create directories
  tags: directories
  file:
  args: "{{ dir }}"
  loop: "{{ base_directories }}"
  loop_control:
    loop_var: "dir"
    label: "{{ dir.path }}"
  when: base_directories is defined

- name: create files
  tags: files
  copy:
  args: "{{ file }}"
  loop: "{{ base_files }}"
  loop_control:
    loop_var: "file"
    label: "{{ file.dest }}"
  when: base_files is defined

- name: disable ufw
  ufw:
    state: disabled
