- name: base-ubuntu role
  hosts: all
  become: true
  vars:
    base_dnsmasq_config: |
      listen-address=127.0.0.1,172.17.0.1
      interface=docker0
      interface=lo
      bind-interfaces
      server=1.1.1.1

    base_openresolv_config: |
      resolv_conf="/etc/resolv.conf"
      name_servers="1.1.1.1"

    base_packages:
      - jq
      - unzip

    base_groups:
      - name: "molecule-test"
        gid: 666

    base_users:
      - name: "molecule"
        uid: 666
        system: true
        shell: "/sbin/nologin"
        group: "molecule-test"
        groups:
          - docker
          - ansible-managed
        append: true
        ssh: https://github.com/nahsi.keys

    base_directories:
      - path: "/opt/molecule"
        owner: "molecule"
        group: "molecule-test"
        mode: "0775"
        state: directory

    base_files:
      - dest: "/opt/molecule/foo"
        content: "bar"
        group: "molecule-test"

    base_sysctl:
      - name: vm.swappiness
        value: 1

    base_limits:
      - domain: '*'
        limit_type: "hard"
        limit_item: "nofile"
        comment: "Increse max open file limit"
        value: 65536

      - domain: '*'
        limit_type: "soft"
        limit_item: "nofile"
        comment: "Increse max open file limit"
        value: 65536
  roles:
    - ansible-base-ubuntu
