- name: stop systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: false
    state: stopped

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: run resolvconf
  command: resolvconf -u

- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    daemon_reload: true
